name: Awesome Research Group
url: http://awesome.example.edu

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: staff
    name: Staff
  - key: postdoc
    name: Researchers
  - key: grad
    name: Graduate Students
  - key: ugrad
    name: Undergraduate Students
  - key: ugrad-alum
    name: Past Undergraduate Students
  - key: collab
    name: Collaborators
  - key: alum
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /#people
  - title: Research
    link: /research.html
  - title: Publications
    link: /publications.html
  - title: Code
    link: /code.html


# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

## Markdown and syntax highlight
# markdown: kramdown
# highlighter: rouge
# highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
# kramdown:
#   input: GFM
#   syntax_highlighter_opts:
#     css_class: 'highlight'
#     span:
#       line_numbers: false
#     block:
#       line_numbers: false
#       start_line: 1

# Plug-ins
plugins:
  - jekyll-email-protect
  # - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll/scholar
  - jemoji
  # - bootstrap
  # - material-sass

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  last_name: Einstein

  style: apa
  locale: en

  source: /bib/
  bibliography: papers.bib
  bibliography_template: bib_entry

  group_by: none
  sort_by: year,month
  order: descending

  query: "@*"
