name: Data Science Research Group
url: https://datascience.dsv.su.se/

exclude: [README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: senior
    name: Senior Researchers
  - key: staff
    name: Staff
  - key: researcher
    name: Research Assistants
  - key: phd
    name: PhD Students
  - key: stud
    name: Students
  - key: affiliated
    name: Affiliated Researchers
  - key: collab
    name: Collaborators
  - key: alumni
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# Setup main page
logo: img/logo/dsgroup.png #img/dsdsv_logo_white_bg.png
banner: img/banners/nodkista.jpg
department_name: Department of Computer and Systems Sciences
department_url: https://dsv.su.se/
university_name: Stockholm University
university_url: https://su.se/


# make pages for the _projects and _research folder
collections:
  projects:
    output: true
  research:
    output: true

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people.html
  - title: Research
    link: /research.html
  - title: Projects
    link: /projects.html
  - title: Data Science Seminars
    link: /seminars.html
  - title: Publications
    link: /publications.html
  #- title: Code
  #  link: /code.html


# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

## Markdown and syntax highlight
# markdown: kramdown
# highlighter: rouge
# highlight_theme: github  # https://github.com/jwarby/jekyll-pygments-themes
# kramdown:
#   input: GFM
#   syntax_highlighter_opts:
#     css_class: 'highlight'
#     span:
#       line_numbers: false
#     block:
#       line_numbers: false
#       start_line: 1

# Plug-ins
plugins:
  - jekyll-email-protect
  # - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll/scholar
  - jemoji

# -----------------------------------------------------------------------------
# Jekyll Scholar
# -----------------------------------------------------------------------------

scholar:

  # last_name: Quintero

  style: apa
  locale: en

  source: /bib/
  bibliography: papers.bib
  bibliography_template: bib_entry

  # group_by: none
  sort_by: year,month
  order: descending

  # query: "@*"
